-- 1. 평균 일일 대여 요금 구하기
SELECT ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV'


-- 2. 재구매가 일어난 상품과 회원 리스트 구하기
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY 1, 2
HAVING COUNT(*) >= 2
ORDER BY 1, 2 DESC


-- 3. 흉부외과 또는 일반외과 의사 목록 출력하기
SELECT DR_NAME, 
       DR_ID, 
       MCDP_CD, 
       DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') as HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD = 'CS' OR MCDP_CD = 'GS'
ORDER BY 4 DESC, 1


-- 4. 역순 정렬하기
SELECT NAME,
       DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC


-- 5. 아픈 동물 찾기
SELECT ANIMAL_ID,
       NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID


-- 6. 어린 동물 찾기
SELECT ANIMAL_ID,
       NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged'
ORDER BY ANIMAL_ID


-- 7. 과일로 만든 아이스크림 고르기
SELECT A.FLAVOR
FROM FIRST_HALF A
LEFT JOIN ICECREAM_INFO B
ON A.FLAVOR = B.FLAVOR
WHERE TOTAL_ORDER > 3000
  AND INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC


-- 8. 동물의 아이디와 이름
SELECT ANIMAL_ID,
       NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID


-- 9. 여러 기준으로 정렬하기
SELECT ANIMAL_ID,
       NAME,
       DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC


-- 10. 상위 n개 레코드
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1


-- 11. 조건에 맞는 회원수 구하기
SELECT COUNT(USER_ID)
FROM USER_INFO
WHERE YEAR(JOINED) = 2021
  AND AGE BETWEEN 20 AND 29


-- 12. 3월에 태어난 여성 회원 목록 출력하기
SELECT MEMBER_ID, 
       MEMBER_NAME, 
       GENDER, 
       DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH) = 3
  AND NOT TLNO IS NULL
  AND GENDER = 'W'
ORDER BY MEMBER_ID


--13. 서울에 위치한 식당 목록 출력하기
SELECT *
FROM (
SELECT A.REST_ID,
       REST_NAME,
       FOOD_TYPE,
       FAVORITES,
       ADDRESS,
       ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO A
LEFT JOIN REST_REVIEW B
ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY 1, 2, 3, 4, 5
ORDER BY 6 DESC,
         4 DESC
) A
WHERE NOT SCORE IS NULL