-- 1. 조건에 맞는 도서와 저자 리스트 출력하기
SELECT B.BOOK_ID,
       A.AUTHOR_NAME,
       DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B
LEFT JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE


-- 2. 상품 별 오프라인 매출 구하기
WITH TEMP_SALES AS (
SELECT P.PRODUCT_CODE,
       SUM(P.PRICE * O.SALES_AMOUNT) SALES
FROM PRODUCT P
LEFT JOIN OFFLINE_SALE O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY 1
)
SELECT *
FROM TEMP_SALES
ORDER BY SALES DESC,
         PRODUCT_CODE


-- 3. 없어진 기록 찾기
SELECT O.ANIMAL_ID,
       O.NAME
FROM ANIMAL_INS I
RIGHT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID


-- 4. 있었는데요 없었습니다
SELECT O.ANIMAL_ID,
       O.NAME
FROM ANIMAL_INS I
RIGHT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME 


-- 5. 오랜 기간 보호한 동물(1)
SELECT I.NAME,
       I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME
LIMIT 3